# Generated by Django 2.2.13 on 2020-06-28 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionArticulos', '0002_auto_20200628_2024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionArticulos.Media')),
                ('interesado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(max_length=80)),
                ('fechaHoraMsg', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionMensajeria.Chat')),
                ('escribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escribe', to=settings.AUTH_USER_MODEL)),
                ('recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='msgs',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gestionMensajeria.Mensaje'),
        ),
    ]
