# Generated by Django 2.2.11 on 2020-04-10 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=240)),
                ('fotoart', models.ImageField(upload_to='articulos')),
                ('accion', models.CharField(choices=[('INTERCAMBIO', 'INTERCAMBIO'), ('DONO', 'DONO'), ('COMPARTO', 'COMPARTO')], max_length=12)),
                ('categoria', models.CharField(choices=[('PELICULAS', 'Películas'), ('SERIES', 'Series'), ('VIDEOJUEGOS', 'Videojuegos'), ('COMICS', 'Cómics'), ('LIBROS', 'Libros'), ('MUSICA', 'Música')], max_length=12, verbose_name='Categoría')),
                ('tags', models.CharField(max_length=100)),
                ('fechaAd', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de adición')),
                ('asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_asignado', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_propietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
