# Generated by Django 2.2.13 on 2020-06-28 18:24

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gestionArticulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=djongo.models.fields.ArrayReferenceField(on_delete=djongo.models.fields.ArrayReferenceField._on_delete, to='gestionArticulos.Tag'),
        ),
    ]
