# Generated by Django 2.2.11 on 2020-06-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionArticulos', '0003_auto_20200417_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='valorado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Medias', to='gestionArticulos.Tag'),
        ),
    ]
