# Generated by Django 2.2.11 on 2020-06-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionArticulos', '0004_auto_20200623_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gestionArticulos.Tag'),
        ),
    ]
