# Generated by Django 2.2.11 on 2020-04-06 18:51

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', djongo.models.fields.EmbeddedField(model_container=django.contrib.auth.models.User, null=True)),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('bio', models.CharField(max_length=150)),
                ('valoracion', models.IntegerField(default=0)),
                ('fechaNacimiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de nacimiento')),
            ],
        ),
    ]
