# Generated by Django 2.2.11 on 2020-03-25 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=35)),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='La contraseña debe tener mínimo 8 caracteres y al menos una letra o número.', regex='^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$')])),
                ('pathAvatar', models.FilePathField(max_length=150)),
                ('bio', models.CharField(max_length=150)),
                ('valoracion', models.IntegerField(blank=True, default=0)),
                ('fechaCreacion', models.DateField(auto_now_add=True)),
                ('fechaNacimiento', models.DateField()),
            ],
        ),
    ]
