# Generated by Django 2.2.11 on 2020-03-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
