# Generated by Django 2.2.11 on 2020-04-08 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioUbicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latUb', models.FloatField(verbose_name='Latitud de la ubicación')),
                ('lngUb', models.FloatField(verbose_name='Longitud de la ubicación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
