# Generated by Django 2.2.11 on 2020-06-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0002_usuarioubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioinfo',
            name='n_valoraciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuarioinfo',
            name='valoracion',
            field=models.FloatField(default=0),
        ),
    ]
