# Generated by Django 2.2.11 on 2020-03-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0002_auto_20200325_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fechaCreacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fechaNacimiento',
        ),
    ]
