# Generated by Django 2.2.11 on 2020-06-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0003_auto_20200623_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioinfo',
            name='valoracion',
            field=models.IntegerField(default=0),
        ),
    ]
