# Generated by Django 2.2.11 on 2020-03-25 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0003_auto_20200325_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(default=datetime.datetime(2020, 3, 25, 13, 49, 36, 175154)),
        ),
    ]
