# Generated by Django 2.2.11 on 2020-03-25 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0004_usuario_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fechaNacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
