# Generated by Django 2.2.11 on 2020-03-25 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0005_auto_20200325_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fechaCreacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
