# Generated by Django 2.2.11 on 2020-03-29 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestionUsuarios', '0007_auto_20200325_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars')),
                ('bio', models.CharField(max_length=150)),
                ('valoracion', models.IntegerField(blank=True, default=0)),
                ('fechaNacimiento', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de nacimiento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
