# Generated by Django 2.2.11 on 2020-04-05 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0010_auto_20200405_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioinfo',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
