# Generated by Django 2.2.11 on 2020-04-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0011_auto_20200405_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioinfo',
            name='valoracion',
            field=models.IntegerField(default=0),
        ),
    ]
