# Generated by Django 2.2.11 on 2020-04-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0012_auto_20200406_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioinfo',
            name='avatar',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
